version: '3.7'

services:
  app:
    container_name: vinopinionsapi-devcontainer
    build:
      context: ..
      dockerfile: .devcontainer/Dockerfile
    ports:
      - 3000:3000
    env_file:
      - .env
    volumes:
      - ..:/workspace
    user: dev

  db:
    container_name: vinopinionsapi-devcontainer-db
    image: postgres:16
    restart: unless-stopped
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
      - POSTGRES_PORT=${POSTGRES_PORT}
    ports:
      - 5432:5432
    volumes:
      - vinopinionsapi-devcontainer-pgdata:/var/lib/postgresql/data

  minio:
    container_name: vinopinionsapi-devcontainer-minio
    image: docker.io/bitnami/minio:latest
    restart: unless-stopped
    ports:
      - '9000:9000'
      - '9001:9001'
    volumes:
      - 'vinopinionsapi-minio-data:/data'
    environment:
      - MINIO_ROOT_USER=${S3_ACCESS_KEY}
      - MINIO_ROOT_PASSWORD=${S3_SECRET_KEY}
      - MINIO_DEFAULT_BUCKETS=${S3_BUCKET}

volumes:
  vinopinionsapi-devcontainer-pgdata:
  vinopinionsapi-minio-data:
