name: Dependabot Auto-Merge

on:
  pull_request:
    branches: ['dependencies']

permissions:
  pull-requests: write

jobs:
  test-unit:
    uses: ./.github/workflows/unit-test.yml
    permissions:
      contents: read # for checkout

  test-e2e:
    uses: ./.github/workflows/e2e-test.yml
    permissions:
      contents: read # for checkout

  approve:
    runs-on: ubuntu-latest
    if: github.actor == 'dependabot[bot]'
    needs:
      - test-e2e
      - test-unit

    steps:
      - name: Dependabot metadata
        id: metadata
        uses: dependabot/fetch-metadata@v1
        with:
          github-token: '${{ secrets.GITHUB_TOKEN }}'
      - name: Approve a PR
        run: gh pr review --approve "$PR_URL"
        env:
          PR_URL: ${{github.event.pull_request.html_url}}
          GH_TOKEN: ${{secrets.GITHUB_TOKEN}}
