name: Deploy Docker Image Test
on:
  push:
    branches: ['developer']

jobs:
  codeql:
    uses: ./.github/workflows/codeql.yml

  eslint:
    uses: ./.github/workflows/eslint.yml

  test-unit:
    uses: ./.github/workflows/unit-test.yml

  test-e2e:
    uses: ./.github/workflows/e2e-test.yml

  publish-test:
    name: Publish Test Docker Image
    runs-on: ubuntu-latest
    environment: test
    needs:
      - codeql
      - eslint
      - test-unit
      - test-e2e

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Extract shortSha
        id: extract_shortSha
        run: echo "::set-output name=shortSha::$(git rev-parse --short ${{ github.sha }})"

      - name: Build and push
        uses: docker/build-push-action@v5
        with:
          context: .
          push: true
          tags: |
            ghcr.io/${{ github.repository }}:${{ vars.DOCKER_IMAGE_TAG }}
            ghcr.io/${{ github.repository }}:${{ github.ref_name }}-${{ steps.extract_shortSha.outputs.shortSha }}
