name: End-to-End test

on:
  push:
    branches: ['developer', 'master']
  pull_request:
    branches: ['developer', 'master']
  schedule:
    - cron: '0 8 * * *'

jobs:
  test:
    name: e2e Test
    runs-on: ubuntu-latest
    permissions:
      contents: read
    services:
      postgres:
        image: postgres
        env:
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: postgres
          options: >-
            --health-cmd pg_isready
            --health-interval 10s
            --health-timeout 5s
            --health-retries 5
    environment: test
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: ${{ vars.NODE_VERSION }}

      - name: Install dependencies
        run: yarn --ignore-scripts --non-interactive --frozen-lockfile

      - name: Run Tests
        run: yarn test:e2e --ci --runInBand
        env:
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: postgres
          POSTGRES_HOST: postgres
          POSTGRES_PORT: 5432
          POSTGRS_DB: test
          NODE_ENV: test
          AUTH_SERVICE_DOMAIN: 'test.vinopinions.spots.host'
          JWT_PRIVATE_KEY: ${{ secrets.JWT_PRIVATE_KEY }}
          JWT_PUBLIC_KEY: ${{ vars.JWT_PUBLIC_KEY }}
