name: test unit

on:
  pull_request:
    branches:
      - developer
      - master
  workflow_call:

jobs:
  test:
    runs-on: ubuntu-latest
    container: node:20.11.0-alpine
    environment: test
    steps:
      - name: Check out repository code
        uses: actions/checkout@v3
        with:
          clean: true

      - name: Install dependencies
        run: yarn --ignore-scripts --non-interactive

      - name: Test formatting
        run: yarn format:check

      - name: Test linting
        run: yarn lint:check

      - name: Run tests
        run: yarn test

      # - name: Test coverage
      #   run: yarn test:cov
